# Generated by Django 5.2.13 on 2026-04-14 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gres_zharnama', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockin',
            old_name='date',
            new_name='date_added',
        ),
        migrations.RemoveField(
            model_name='stockin',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='waste_meters',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stockin',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='material',
            name='stock_meters',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='meters_needed',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gres_zharnama.material'),
        ),
    ]
