# Generated by Django 5.2.13 on 2026-04-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gres_zharnama', '0002_rename_date_stockin_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
